#!/bin/sh

if [ ! -f ~/.gtkdocpo ];then
    printf "\033[1;31m==> "说明："\033[1;0m\033[1;1m  请在下面输入您的googlecode用户名：\033[1;0m\n" >&2;
    read username
    echo "username=$username" > ~/.gtkdocpo
fi

[ -d $HOME/bin ] || mkdir $HOME/bin
cp ./gtkdocpo ~/bin/
cp ./gadt-mkhtml ~/bin
cp ./gadt-autotrans ~/bin
