#!/bin/sh

if [ ! -f ~/.gtkdocpo ];then
    printf "\033[1;31m==> "说明："\033[1;0m\033[1;1m请在下面输入您的googlecode用户名(@gmail.com之前的部分)：\033[1;0m\n" >&2;
    echo -n "请输入:"
    read username
    while [ -z $username ]
    do
	    echo -n "请输入:"
	    read username
    done
    printf "\033[1;0m\033[1;1m  你输入的用户名为==>\033[1;31m "$username" \033[1;0m\n" >&2;
    printf "\033[1;0m\033[1;1m  以后还可以通过修改 ~/.gtkdocpo 文件来改变。\033[1;0m\n" >&2;
    echo "username=$username" > ~/.gtkdocpo
fi

[ -d $HOME/bin ] || mkdir $HOME/bin
cp ./gtkdocpo ~/bin/
cp ./gadt-mkhtml ~/bin
cp ./gadt-autotrans ~/bin
