#!/bin/sh
# File: update-sgml.sh
# Summary: This is a ...
# Author: yetist <yetist@gmail.com>
# Version: 2009-10-08 19:21:27
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source ./build.rc
startdir=`pwd`
pkgfile=`basename $source`
tmpdir=$startdir/tmp
[ -d $tmpdir ] || mkdir $tmpdir
srcdir=$tmpdir/$pkgname-$pkgver
source ./build.rc

if [ ! -d $srcdir ];then
	echo "不存在源代码目录"
	echo "正在下载源文件..."
	$(
	cd $tmpdir;
	[ -f $pkgfile ] || wget $source;
	file $pkgfile |grep bzip && tar -jxf $pkgfile
	file $pkgfile |grep gzip && tar -zxf $pkgfile
	)
fi

olddocs=`ls -d $startdir/docs-*`
if [ -d $olddocs ];then
	for f in `find $olddocs -name "*.sgml"`;
	do
		filename=${f#$olddocs\/}
		vim -d $docdir/$filename ${olddocs}/$filename
	done
fi
