#!/bin/sh
####################################################################################
#一、[目录]
#1.  (yetist)glib-docs.sgml
#二、[GLib Overview]
#1.  (yetist)building.sgml
#2.  (yetist)cross.sgml
#3.  (lerosua)compiling.sgml
#4.  (lerosua)running.sgml
#5.  (wzssyqa)changes.sgml
#6.  (kovchou)regex-syntax.sgml
#7.  (chuangshengguan)resources.sgml
#三、[GLib Fundamentals]
#1.  (功夫熊猫)tmpl/version.sgml 				gutils.po
#2.  (NULL)tmpl/types.sgml
#3.  (cnkilior)tmpl/limits.sgml
#4.  (NULL)tmpl/macros.sgml
#5.  (NULL)tmpl/type_conversion.sgml
#6.  (NULL)tmpl/byte_order.sgml
#7.  (NULL)tmpl/numerical.sgml
#8.  (R.4ntix)tmpl/macros_misc.sgml
#9.  (NULL)tmpl/atomic_operations.sgml
#四、[GLib Core Application Support]
#1.  (unknown)tmpl/main.sgml				gmain.po,gpoll.po
#2.  (unknown)tmpl/threads.sgml 				gthread.po
#3.  tmpl/thread_pools.sgml 			gthreadpool.po
#4.  tmpl/async_queues.sgml 			gasyncqueue.po
#5.  tmpl/modules.sgml
#6.  tmpl/memory.sgml 				gmem.po
#7.  tmpl/iochannels.sgml 			giochannel.po
#8.  tmpl/error_reporting.sgml 			gerror.po
#9.  tmpl/warnings.sgml
#10. tmpl/messages.sgml
#五、[GLib Utilities]
#1.  tmpl/string_utils.sgml 			gprintf.po,gstrfuncs.po
#2.  tmpl/conversions.sgml 			gconvert.po
#3.  tmpl/unicode.sgml 				gunibreak.po,gunicollate.po,gunidecomp.po,guniprop.po,gutf8.po
#4.  tmpl/base64.sgml				gbase64.po
#5.  tmpl/checksum.sgml 			gchecksum.po
#6.  tmpl/i18n.sgml
#7.  tmpl/date.sgml 				gdate.po
#8.  tmpl/random_numbers.sgml 			grand.po
#9.  tmpl/hooks.sgml
#10. tmpl/misc_utils.sgml 			gqsort.po
#11. tmpl/scanner.sgml
#12. tmpl/completion.sgml 			gcompletion.po
#13. tmpl/timers.sgml 				gtimer.po
#14. tmpl/spawn.sgml 				gspawn.po
#15. tmpl/fileutils.sgml 			gfileutils.po,gdir.po,gmappedfile.po,gstdio.po
#16. tmpl/gurifuncs.sgml 			gurifuncs.po
#17. tmpl/shell.sgml 				gshell.po
#18. tmpl/option.sgml 				goption.po
#19. tmpl/patterns.sgml
#20. tmpl/gregex.sgml 				gregex.po
#21. tmpl/markup.sgml 				gmarkup.po
#22. tmpl/keyfile.sgml 				gkeyfile.po
#23. tmpl/bookmarkfile.sgml 			gbookmarkfile.po
#24. tmpl/testing.sgml 				gtestutils.po
#25. tmpl/windows.sgml 				gwin32.po
#六、[GLib Data Types]
#1.  tmpl/memory_slices.sgml
#2.  tmpl/memory_chunks.sgml
#3.  tmpl/linked_lists_double.sgml 		glist.po
#4.  tmpl/linked_lists_single.sgml 		gslist.po
#5.  tmpl/queue.sgml 				gqueue.po
#6.  tmpl/sequence.sgml 			gsequence.po
#7.  tmpl/trash_stack.sgml
#8.  tmpl/hash_tables.sgml 			ghash.po
#9.  tmpl/strings.sgml 				gstring.po
#10. tmpl/string_chunks.sgml
#11. tmpl/arrays.sgml
#12. tmpl/arrays_pointer.sgml 			garray.po
#13. tmpl/arrays_byte.sgml
#14. tmpl/trees-binary.sgml 			gtree.po
#15. tmpl/trees-nary.sgml 			gnode.po
#16. tmpl/quarks.sgml
#17. tmpl/datalist.sgml
#18. tmpl/datasets.sgml 			gdataset.po
#19. tmpl/relations.sgml
#20. tmpl/caches.sgml
#21. tmpl/allocators.sgml
#七、[GLib Tools]
#1.  glib-gettextize.xml
#2.  gtester.xml
#3.  gtester-report.xml
####################################################################################
#此文件的格式如下
#作者 邮箱 sgml文件数组 po文件数组
#sgml_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com sgml_files=(glib-docs.sgml,building.sgml,cross.sgml) po_files=()
lerosua lerosua@gmail.com sgml_files=(compiling.sgml,running.sgml) po_files=()
wzssyqa wzssyqa@gmail.com sgml_files=(changes.sgml) po_files=()
kovchou kovchou@gmail.com sgml_files=(regex-syntax.sgml) po_files=()
NULL chuangshengguan@gmail.com sgml_files=(tmpl/atomic_operations.sgml) po_files=()
cnkilior zhangn1985@gmail.com sgml_files=(tmpl/limits.sgml) po_files=()
功夫熊猫 toubuhun@163.com sgml_files=(tmpl/version.sgml) po_files=()
R.4ntix r.4ntix@gmail.com sgml_files=(tmpl/macros_misc.sgml) po_files=()
#liuruile liuruile@gmail.com sgml_files=(regex-syntax.sgml) po_files=()
########计划翻译的文档###############
unknown unknown@nomail.com sgml_files=(tmpl/main.sgml,tmpl/threads.sgml) po_files=(gutils.po,gmain.po,gpoll.po,gthread.po)
