#!/bin/sh
#一、[xmlpo 文件列表]
#1.  glib-docs.po                (yetist)
#2.  building.po                 (yetist)
#3.  cross.po                    (yetist)
#4.  compiling.po                (lerosua)
#5.  running.po                  (lerosua)
#6.  changes.po                  (wzssyqa)
#7.  regex-syntax.po             (kovchou)
#8.  gvariant-varargs.po         (chuangshengguan)
#9.  resources.po                (chuangshengguan)
#10. glib-gettextize.po
#11. gtester.po
#12. gtester-report.po

#二、[po 文件列表]
#1.  galloca.po
#1.  garray.po
#1.  gasyncqueue.po
#1.  gatomic.po
#1.  gbase64.po
#1.  gbitlock.po
#1.  gbookmarkfile.po
#1.  gcache.po
#1.  gchecksum.po
#1.  gcompletion.po
#1.  gconvert.po
#1.  gdataset.po
#1.  gdate.po
#1.  gdatetime.po
#1.  gdir.po
#1.  gerror.po
#1.  gfileutils.po
#1.  ghash.po
#1.  ghostutils.po
#1.  giochannel.po
#1.  giounix.po
#1.  giowin32.po
#1.  gkeyfile.po
#1.  glist.po
#1.  gmain.po
#1.  gmappedfile.po
#1.  gmarkup.po
#1.  gmem.po
#1.  gmessages.po
#1.  gnode.po
#1.  goption.po
#1.  gpattern.po
#1.  gpoll.po
#1.  gprintf.po
#1.  gqsort.po
#1.  gqueue.po
#1.  grand.po
#1.  gregex.po
#1.  grel.po
#1.  gsequence.po
#1.  gshell.po
#1.  gslist.po
#1.  gspawn.po
#1.  gstdio.po
#1.  gstrfuncs.po
#1.  gstring.po
#1.  gtestutils.po
#1.  gthreadpool.po
#1.  gthread.po
#1.  gtimer.po
#1.  gtimezone.po
#1.  gtree.po
#1.  gtypes.po
#1.  gunibreak.po
#1.  gunicollate.po
#1.  gunidecomp.po
#1.  guniprop.po
#1.  gurifuncs.po
#1.  gutf8.po
#1.  gutils.po
#1.  gvariant-core.po
#1.  gvariant-parser.po
#1.  gvariant.po
#1.  gvarianttype.po
#1.  gwin32.po
#
####################################################################################
#此文件的格式如下
#作者 邮箱 sgml文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com xmlpo_files=(glib-docs.po) po_files=()
lerosua lerosua@gmail.com xmlpo_files=(compiling.po,running.po) po_files=()
wzssyqa wzssyqa@gmail.com xmlpo_files=(changes.po) po_files=()
kovchou kovchou@gmail.com xmlpo_files=(regex-syntax.po) po_files=()
NULL chuangshengguan@gmail.com xmlpo_files=() po_files=()
cnkilior zhangn1985@gmail.com xmlpo_files=() po_files=()
功夫熊猫 toubuhun@163.com xmlpo_files=() po_files=()
R.4ntix r.4ntix@gmail.com xmlpo_files=() po_files=(gthreadpool.po)
zhang mymzhang@gmail.com xmlpo_files=() po_files=(gthread.po)
piuruile liuruile@gmail.com xmlpo_files=() po_files=(garray.po)
########计划翻译的文档###############
unknown unknown@nomail.com xmlpo_files=() po_files=(gutils.po,gmain.po,gpoll.po,gasyncqueue.po)
####################################################################################
