#!/bin/sh
####################################################################################
#一、[Introduction]
#1.  gobject-docs.sgml
#二、[Concepts]
#1.  tut_intro.xml
#2.  tut_gtype.xml
#3.  tut_gobject.xml
#4.  tut_gsignal.xml
#三、[Tools Reference]
#1.  glib-mkenums.xml
#2.  glib-genmarshal.xml
#3.  gobject-query.xml
#四、[Tutorial]
#1.  tut_howto.xml
#五、[Related Tools]
#1.  tut_tools.xml
####################################################################################
#此文件的格式如下
#作者 邮箱 sgml文件数组 po文件数组
#sgml_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com sgml_files=(gobject-docs.sgml,tut_gtype.xml) po_files=()
黑孩儿 admin@heiher.info sgml_files=(tut_gtype.xml) po_files=()
########计划翻译的文档###############
unknown unknown@nomail.com sgml_files=() po_files=()
