#!/bin/sh
#此文件的格式如下
#作者 邮箱 sgml文件数组 po文件数组
#sgml_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示无人认领，未开始翻译
#作者名为finished表示已内容已经翻译完成。
lerosua lerosua@gmail.com sgml_files=(gdk-pixbuf-csource.xml,gdk-pixbuf-from-drawables.sgml) po_files=(gdk-pixbuf-animation.po,gdk-pixbuf-data.po)
yetist yetist@gmail.com sgml_files=(gdk-pixbuf-query-loaders.xml,gdk-pixbuf-rendering.sgml) po_files=(gdk-pixbuf-io.po,gdk-pixbuf-loader.po)
unknown unknown@nomail.com sgml_files=(gdk-pixbuf.sgml,porting-from-imlib.sgml,tmpl/animation.sgml,tmpl/creating.sgml,tmpl/file-loading.sgml,tmpl/file-saving.sgml,tmpl/gdk-pixbuf-loader.sgml,tmpl/gdk-pixbuf-xlib-from-drawables.sgml,tmpl/gdk-pixbuf-xlib-init.sgml,tmpl/gdk-pixbuf-xlib-rendering.sgml,tmpl/gdk-pixbuf-xlib-rgb.sgml,tmpl/gdk-pixbuf.sgml,tmpl/initialization_versions.sgml,tmpl/inline.sgml,tmpl/module_interface.sgml,tmpl/refcounting.sgml,tmpl/scaling.sgml,tmpl/util.sgml) po_files=(gdk-pixbuf-scale.po,gdk-pixbuf-simple-anim.po,gdk-pixbuf-util.po,gdk-pixbuf.po,gdk-pixdata.po)
