#!/bin/sh
#一、[xmlpo 文件列表]
#1. libgksu-docs.pot
#二、[po 文件列表]
#1. gksu-run-helper.pot
#2. libgksu.pot
#
####################################################################################
#此文件的格式如下
#作者 邮箱 xmlpo文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示无人认领，未开始翻译
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com xmlpo_files=() po_files=(libgksu.po)
lerosua lerosua@gmail.com xmlpo_files=() po_files=(libgksu.po)
5451vs5451 5451vs5451@gmail.com xmlpo_files=() po_files=(libgksu.po)
########计划翻译的文档###############
unknown unknown@gmail.com xmlpo_files=() po_files=(libgksu.po)
finished finished@nomail.com xmlpo_files=(libgksu-docs.po) po_files=(gksu-run-helper.po)
####################################################################################
