#!/bin/sh
#此文件的格式如下
#作者 邮箱 sgml文件数组 po文件数组
#sgml_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示无人认领，未开始翻译
#作者名为finished表示内容已经翻译完成。
yetist yetist@gmail.com sgml_files=(credits.xml,libgksu-docs.sgml,tmpl/libgksu.sgml) po_files=(gksu-run-helper.po,libgksu.po)
lerosua lerosua@gmail.com sgml_files=(credits.xml,libgksu-docs.sgml,tmpl/libgksu.sgml) po_files=(gksu-run-helper.po,libgksu.po)
5451vs5451 5451vs5451@gmail.com sgml_files=(credits.xml,libgksu-docs.sgml,tmpl/libgksu.sgml) po_files=(gksu-run-helper.po,libgksu.po)
unknown unknown@gmail.com sgml_files=(credits.xml,libgksu-docs.sgml,tmpl/libgksu.sgml) po_files=(gksu-run-helper.po,libgksu.po)
finished finished@nomail.com sgml_files=() po_files=()
