#!/bin/sh
####################################################################################
#一、[xmlpo 文件列表]
#
#二、[po 文件列表]
#
####################################################################################
#此文件的格式如下
#作者 邮箱 xmlpo文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com xmlpo_files=(gobject-docs.po,tut_gtype.po) po_files=()
黑孩儿 admin@heiher.info xmlpo_files=(tut_gtype.po) po_files=()
########计划翻译的文档###############
unknown unknown@nomail.com sgml_files=() po_files=()
