#!/bin/sh
####################################################################################
#一、[xmlpo 文件列表]
#1.  glib-genmarshal.po
#2.  glib-mkenums.po
#3.  gobject-docs.po
#4.  gobject-query.po
#5.  tut_gobject.po
#6.  tut_gsignal.po
#7.  tut_gtype.po           (黑孩儿翻译，yetist整理)
#8.  tut_howto.po
#9.  tut_intro.po
#10. tut_tools.po
#
#二、[po 文件列表]
#1.  gbinding.po
#2.  gboxed.po
#3.  gclosure.po
#4.  genums.po
#5.  gobject.po
#6.  gparam.po
#7.  gparamspecs.po
#8.  gsignal.po
#9.  gsourceclosure.po
#10. gtypemodule.po
#11. gtypeplugin.po
#12. gtype.po
#13. gvaluearray.po
#14. gvaluecollector.po
#15. gvalue.po
#16. gvaluetypes.po
#
####################################################################################
#此文件的格式如下
#作者 邮箱 xmlpo文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com xmlpo_files=(gobject-docs.po,tut_gtype.po) po_files=()
黑孩儿 admin@heiher.info xmlpo_files=(tut_gtype.po) po_files=()
antkillerfarm antkillerfarm@gmail.com xmlpo_files=(tut_intro.po) po_files=()
########计划翻译的文档###############
unknown unknown@nomail.com sgml_files=() po_files=()
