#!/bin/sh
#一、[目录]
#1.  (yetist)gdk-docs.sgml
#二、[API Reference]
#1.  (yetist)tmpl/general.sgml 		gdk.po
#2.  multihead.sgml
#3.  tmpl/gdkdisplay.sgml		gdkdisplay.po
#4.  tmpl/gdkdisplaymanager.sgml 	gdkdisplaymanager.po
#5.  tmpl/gdkscreen.sgml 		gdkscreen.po
#6.  tmpl/regions.sgml 			gdkregion-generic.po,gdkpolyreg-generic.po,gdkrectangle.po
#7.  tmpl/gcs.sgml 			gdkgc.po
#8.  tmpl/drawing.sgml 			gdkdraw.po
#9.  tmpl/pixmaps.sgml
#10. tmpl/rgb.sgml 			gdkrgb.po
#11. tmpl/images.sgml 			gdkimage.po
#12. tmpl/pixbufs.sgml 			gdkpixbuf-drawable.po,gdkpixbuf-render.po
#13. tmpl/colors.sgml 			gdkcolor.po
#14. tmpl/visuals.sgml 			gdkvisual.po
#15. tmpl/fonts.sgml 			gdkfont.po
#16. tmpl/cursors.sgml 			gdkcursor.po
#17. tmpl/windows.sgml 			gdkwindow.po
#18. tmpl/events.sgml 			gdkevents.po
#19. tmpl/event_structs.sgml
#20. tmpl/keys.sgml 			gdkkeys.po,gdkkeyuni.po
#21. tmpl/selections.sgml 		gdkselection.po
#22. tmpl/dnd.sgml 			gdkdnd.po
#23. tmpl/properties.sgml
#24. tmpl/threads.sgml
#25. tmpl/input.sgml
#26. tmpl/input_devices.sgml
#27. tmpl/pango_interaction.sgml 	gdkpango.po
#28. tmpl/cairo_interaction.sgml 	gdkcairo.po
#29. tmpl/x_interaction.sgml
#30. tmpl/gdkapplaunchcontext.sgml 	gdkapplaunchcontext.po
#31. tmpl/gdktesting.sgml
#
#此文件的格式如下
#作者 邮箱 sgml文件数组 po文件数组
#sgml_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示无人认领，未开始翻译
#作者名为finished表示已内容已经翻译完成。
yetist yetist@gmail.com sgml_files=(gdk-docs.sgml,tmpl/general.sgml) po_files=(gdk.po)
unknown unknown@nomail.com sgml_files=(tmpl/pango_interaction.sgml) po_files=(gdkpango.po)
