#!/bin/sh
#
#############################################
#一、[xmlpo 文件列表]
#01. building.po
#02. compiling.po (天堂之吻翻译，yetist整理)
#03. drawing-model.po (Ekd123翻译，yetist整理)
#04. getting_started.po
#05. glossary.po
#06. gtk-docs.po
#07. gtk-query-immodules-3.0.po
#08. gtk-update-icon-cache.po
#09. migrating-2to3.po
#10. migrating-checklist.po
#11. migrating-GtkApplication.po
#12. migrating-GtkStyleContext.po
#13. osx.po
#14. overview.po
#15. question_index.po
#16. resources.po
#17. running.po
#18. text_widget.po
#19. tree_widget.po
#20. visual_index.po
#21. windows.po
#22. x11.po
#
#############################################
#二、[po 文件列表]
#01.   gtkaboutdialog.po
#02.   gtkaccelgroup.po
#03.   gtkaccellabel.po
#04.   gtkaccelmap.po
#05.   gtkaccessible.po
#06.   gtkactiongroup.po
#07.   gtkaction.po
#08.   gtkactivatable.po
#09.   gtkadjustment.po
#10.   gtkalignment.po
#11.   gtkappchooserbutton.po
#12.   gtkappchooserdialog.po
#13.   gtkappchooser.po
#14.   gtkappchooserwidget.po
#15.   gtkapplication.po
#16.   gtkarrow.po
#17.   gtkaspectframe.po
#18.   gtkassistant.po
#19.   gtkbbox.po
#20.   gtkbindings.po
#21.   gtkbin.po
#22.   gtkborder.po
#23.   gtkbox.po
#24.   gtkbuildable.po
#25.   gtkbuilder.po
#26.   gtkbutton.po
#27.   gtkcalendar.po
#28.   gtkcellareabox.po
#29.   gtkcellareacontext.po
#30.   gtkcellarea.po
#31.   gtkcelleditable.po
#32.   gtkcelllayout.po
#33.   gtkcellrendereraccel.po
#34.   gtkcellrenderercombo.po
#35.   gtkcellrendererpixbuf.po
#36.   gtkcellrenderer.po
#37.   gtkcellrendererprogress.po
#38.   gtkcellrendererspinner.po
#39.   gtkcellrendererspin.po
#40.   gtkcellrenderertext.po
#41.   gtkcellrenderertoggle.po
#42.   gtkcellview.po
#43.   gtkcheckbutton.po
#44.   gtkcheckmenuitem.po
#45.   gtkclipboard.po
#46.   gtkcolorbutton.po
#47.   gtkcolorseldialog.po
#48.   gtkcolorsel.po
#49.   gtkcombobox.po
#50.   gtkcomboboxtext.po
#51.   gtkcontainer.po
#52.   gtkcssprovider.po
#53.   gtkcustompaperunixdialog.po
#54.   gtkdialog.po
#55.   gtkdnd.po
#56.   gtkdnd-quartz.po
#57.   gtkdrawingarea.po
#58.   gtkeditable.po
#59.   gtkentrybuffer.po
#60.   gtkentrycompletion.po
#61.   gtkentry.po
#62.   gtkenums.po
#63.   gtkeventbox.po
#64.   gtkexpander.po
#65.   gtkfilechooserbutton.po
#66.   gtkfilechooserdialog.po
#67.   gtkfilechooserembed.po
#68.   gtkfilechooserentry.po
#69.   gtkfilechooser.po
#70.   gtkfilechooserutils.po
#71.   gtkfilechooserwidget.po
#72.   gtkfilefilter.po
#73.   gtkfilesystemmodel.po
#74.   gtkfixed.po
#75.   gtkfontbutton.po
#76.   gtkfontsel.po
#77.   gtkframe.po
#78.   gtkgradient.po
#79.   gtkgrid.po
#80.   gtkhandlebox.po
#81.   gtkhbox.po
#82.   gtkhscale.po
#83.   gtkhscrollbar.po
#84.   gtkhsv.po
#85.   gtkiconcachevalidator.po
#86.   gtkiconfactory.po
#87.   gtkicontheme.po
#88.   gtkiconview.po
#89.   gtkimagemenuitem.po
#90.   gtkimage.po
#91.   gtkimcontext.po
#92.   gtkimcontextsimple.po
#93.   gtkimmodule.po
#94.   gtkimmulticontext.po
#95.   gtkinfobar.po
#96.   gtkinvisible.po
#97.   gtkkeyhash.po
#98.   gtklabel.po
#99.   gtklayout.po
#100.  gtklinkbutton.po
#101.  gtkliststore.po
#102.  gtkmain.po
#103.  gtkmenubar.po
#104.  gtkmenuitem.po
#105.  gtkmenu.po
#106.  gtkmenushell.po
#107.  gtkmenutoolbutton.po
#108.  gtkmessagedialog.po
#109.  gtkmisc.po
#110.  gtkmodules.po
#111.  gtkmountoperation.po
#102.  gtknotebook.po
#103.  gtknumerableicon.po
#104.  gtkoffscreenwindow.po
#105.  gtkorientable.po
#106.  gtkpagesetup.po
#107.  gtkpagesetupunixdialog.po
#108.  gtkpaned.po
#109.  gtkpapersize.po
#110.  gtkpathbar.po
#111.  gtkplug.po
#112.  gtkprintbackend.po
#113.  gtkprintcontext.po
#114.  gtkprinteroptionset.po
#115.  gtkprinter.po
#116.  gtkprintjob.po
#117.  gtkprintoperation.po
#118.  gtkprintoperationpreview.po
#119.  gtkprintoperation-unix.po
#120.  gtkprintsettings.po
#121.  gtkprintunixdialog.po
#122.  gtkprogressbar.po
#123.  gtkradioaction.po
#124.  gtkradiobutton.po
#125.  gtkradiomenuitem.po
#126.  gtkradiotoolbutton.po
#127.  gtkrange.po
#128.  gtkrc.po
#129.  gtkrecentaction.po
#130.  gtkrecentchooserdialog.po
#131.  gtkrecentchoosermenu.po
#132.  gtkrecentchooser.po
#133.  gtkrecentchooserutils.po
#134.  gtkrecentchooserwidget.po
#135.  gtkrecentfilter.po
#136.  gtkrecentmanager.po
#137.  gtkscalebutton.po
#138.  gtkscale.po
#139.  gtkscrollable.po
#140.  gtkscrollbar.po
#141.  gtkscrolledwindow.po
#142.  gtkselection.po
#143.  gtkseparatormenuitem.po
#144.  gtkseparator.po
#145.  gtkseparatortoolitem.po
#146.  gtksettings.po
#147.  gtkshow.po
#148.  gtksizegroup.po
#149.  gtksizegroup-private.po
#150.  gtksizerequest.po
#151.  gtksocket.po
#152.  gtkspinbutton.po
#153.  gtkspinner.po
#154.  gtkstatusbar.po
#155.  gtkstatusicon.po
#156.  gtkstock.po
#157.  gtkstylecontext.po
#158.  gtkstyle.po
#159.  gtkstyleproperties.po
#160.  gtkstyleprovider.po
#161.  gtkswitch.po
#162.  gtksymboliccolor.po
#163.  gtktable.po
#164.  gtktestutils.po
#165.  gtktextattributes.po
#166.  gtktextbtree.po
#167.  gtktextbuffer.po
#168.  gtktextbufferrichtext.po
#169.  gtktextchild.po
#170.  gtktextiter.po
#171.  gtktextlayout.po
#172.  gtktextmark.po
#173.  gtktexttag.po
#174.  gtktexttagtable.po
#175.  gtktextview.po
#176.  gtkthemingengine.po
#177.  gtktimeline.po
#178.  gtktoggleaction.po
#179.  gtktogglebutton.po
#180.  gtktoggletoolbutton.po
#181.  gtktoolbar.po
#182.  gtktoolbutton.po
#183.  gtktoolitemgroup.po
#184.  gtktoolitem.po
#185.  gtktoolpalette.po
#186.  gtktoolshell.po
#187.  gtktooltip.po
#188.  gtktreednd.po
#189.  gtktreemenu.po
#190.  gtktreemodelfilter.po
#191.  gtktreemodel.po
#192.  gtktreemodelsort.po
#193.  gtktreeselection.po
#194.  gtktreesortable.po
#195.  gtktreestore.po
#196.  gtktreeviewcolumn.po
#197.  gtktreeview.po
#198.  gtkuimanager.po
#199.  gtkvbbox.po
#200.  gtkvbox.po
#201.  gtkversion.po
#202.  gtkviewport.po
#203.  gtkvolumebutton.po
#204.  gtkvpaned.po
#205.  gtkvscale.po
#206.  gtkvscrollbar.po
#207.  gtkvseparator.po
#208.  gtkwidgetpath.po
#209.  gtkwidget.po
#210.  gtkwindow.po
#211.  gtkxembed.po
#212.  updateiconcache.po
#
####################################################################################
#此文件的格式如下
#作者 邮箱 xmlpo文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示无人认领，未开始翻译
#作者名为finished表示已内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com xmlpo_files=() po_files=()
wei weihuoya@126.com xmlpo_files=(compiling.po,getting_started.po,overview.po,windows.po) po_files=(gtkcolorbutton.po,gtkhbox.po,gtkvbox.po)
MikeMa zhtx10@gmail.com xmlpo_files=(gtk-docs.po) po_files=()
天堂之吻 zelda_ok@163.com xmlpo_files=(compiling.po) po_files=()
Ekd123 noname@unknown.domain xmlpo_files=(running.po) po_files=()
########待校订的文档########################################
review html_files=(gtk3-Feature-Test-Macros.html) xmlpo_files=() po_files=(gtkversion.po)
review html_files=(gtk-running.html) xmlpo_files=(running.po) po_files=()
review html_files=(index.html) xmlpo_files=(gtk-docs.po) po_files=()
########完成翻译的文档#################################################
finished yetist@gamil.com xmlpo_files=() po_files=(gtkprinteroptionset.po)
####################################################################################
