#!/bin/sh
#一、[xmlpo 文件列表]
#1.  gdk-docs.pot
#
#二、[po 文件列表]
#01. gdkapplaunchcontext.po
#02. gdkcairo.po
#03. gdkcolor.po
#04. gdkcursor.po
#05. gdkdevicemanager.po
#06. gdkdevice.po
#07. gdkdisplaymanager.po
#08. gdkdisplay.po
#09. gdkdnd.po
#10. gdkevents.po
#11. gdkkeys.po
#12. gdkkeyuni.po
#13. gdkmain.po
#14. gdkoffscreenwindow.po
#15. gdkpango.po
#16. gdkpixbuf-drawable.po
#17. gdk.po
#18. gdkproperty.po
#19. gdkrectangle.po
#20. gdkrgba.po
#21. gdkscreen.po
#22. gdkselection.po
#23. gdktestutils.po
#24. gdkthreads.po
#25. gdktypes.po
#26. gdkvisual.po
#27. gdkwindow.po
#
####################################################################################
#此文件的格式如下
#作者 邮箱 xmlpo文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
########已经和正在翻译的文档###############
yetist yetist@gmail.com xmlpo_files=(gdk-docs.sgml) po_files=(gdk.po)
########计划翻译的文档###############
unknown unknown@nomail.com xmlpo_files=() po_files=(gdkpango.po)
####################################################################################
