#!/bin/sh

if [ ! -f ~/.gtkdocpo ];then
    printf "\033[1;31m==> "说明："\033[1;0m\033[1;1m  请在下面输入您的googlecode用户名：\033[1;0m\n" >&2;
    read username
    echo "username=$username" > ~/.gtkdocpo
fi

if [ `id -u` -eq 0 ];then
	cp ./gtkdocpo /usr/bin/
	cp ./gadt-mkhtml /usr/bin
	cp ./gadt-autotrans /usr/bin
else
	[ -d $HOME/bin ] || mkdir $HOME/bin
	echo $PATH|grep "$HOME/bin:" >/dev/null|| $( echo "export PATH=~/bin:$PATH" >> ~/.bashrc; source ~/.bashrc)
	cp ./gtkdocpo ~/bin/
	cp ./gadt-mkhtml ~/bin
	cp ./gadt-autotrans ~/bin
fi
