#!/bin/sh
#一、[xmlpo 文件列表]
#1. gdk-pixbuf-csource.po
#2. gdk-pixbuf-from-drawables.po
#3. gdk-pixbuf.po
#4. gdk-pixbuf-query-loaders.po
#5. gdk-pixbuf-rendering.po
#
#二、[po 文件列表]
#1. gdk-pixbuf-animation.po
#2. gdk-pixbuf-data.po
#3. gdk-pixbuf-io.po
#4. gdk-pixbuf-loader.po
#5. gdk-pixbuf.po
#6. gdk-pixbuf-scale.po
#7. gdk-pixbuf-simple-anim.po
#8. gdk-pixbuf-util.po
#9. gdk-pixdata.po
#
####################################################################################
#此文件的格式如下
#作者 邮箱 xmlpo文件数组 po文件数组
#xmlpo_files和po_files数组内容以","分隔，中间不要使用空格，否则项目脚本将出错。
#作者名为unknown表示计划翻译，但目前还无人认领
#作者名为finished表示内容已经翻译完成。
####################################################################################
##################################已经和正在翻译的文档####################################
yetist yetist@gmail.com xmlpo_files=(gdk-pixbuf-from-drawables.po,gdk-pixbuf-query-loaders.po,gdk-pixbuf-rendering.po) po_files=(gdk-pixbuf-animation.po,gdk-pixbuf.po,gdk-pixbuf-loader.po)
lerosua lerosua@gmail.com xmlpo_files=() po_files=()
#####################################计划翻译的文档##############################
unknown unknown@nomail.com xmlpo_files=() po_files=()
###################################需要审查的文件列表############################
review html_files=(gdk-pixbuf-csource.html) xmlpo_files=(gdk-pixbuf-csource.po) po_files=()
review html_files=(index.html)              xmlpo_files=(gdk-pixbuf.po)         po_files=()
review html_files=(gdk-pixbuf-Scaling.html) xmlpo_files=()                      po_files=(gdk-pixbuf-scale.po)
######################################翻译完成的文档#######################################
finished finished@nomail.com xmlpo_files=() po_files=()
####################################################################################
